### ISSUE TITLE
Date from published docker container is from the 1970s~

### ISSUE THREAD

**Issue by bmschwa** [dvankley/firefly-plaid-connector-2#120]
The [docker images](https://github.com/dvankley/firefly-plaid-connector-2/pkgs/container/firefly-plaid-connector-2) that get published to ghcr.io are all fine.   However, when I pull them into my synology NAS, they show up having been published in 1979.

![image](https://github.com/user-attachments/assets/02220d48-cac9-4f14-b2af-981cf57e3549)

Here's the same from the command line using this command:
` sudo docker history --format "{{.ID}}: {{.CreatedSince}} {{.CreatedAt}} {{.CreatedBy}} {{.Size}} {{.Comment}}" ghcr.io/dvankley/firefly-plaid-connector-2`

![image](https://github.com/user-attachments/assets/f888399e-39e0-4646-82f5-a1cce9d61811)

**Comment by bmschwa** [comment]
Need to modify either the POM or the gradle config... https://stackoverflow.com/a/76143949

**Comment by dvankley** [comment]
Thanks for pointing this out. Should be fixed in the latest release.
