### ISSUE TITLE
Can't start docker image or standalone Java: exception creating SyncHelper bean

### ISSUE THREAD

**Issue by dwildstr** [dvankley/firefly-plaid-connector-2#122]
Trying to run either the JAR or to start up a docker-compose image, I'm getting a Java error; this might somehow be a result of a bad configuration YAML, although I made pretty vanilla modifications (giving my Plaid and Firefly authentication details, and setting my Firefly URL) to the default application.yml.

I've attached the results of attempting to run the docker image (in debug mode) below; what appears to be the first comprehensible error is
```
s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fireflyPlaidConnector2Application': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'batchSyncRunner' defined in file [/workspace/BOOT-INF/classes/net/djvk/fireflyPlaidConnector2/sync/BatchSyncRunner.class]: Unsatisfied dependency expressed through constructor parameter 4: Error creating bean with name 'syncHelper' defined in file [/workspace/BOOT-INF/classes/net/djvk/fireflyPlaidConnector2/sync/SyncHelper.class]: Unexpected exception during bean creation
```
which suggests that there's some sort of error in SyncHelper which is cascading to its dependencies? I'll freely admit to ignorance about Java generally and the Spring framework in particular, so I don't know what could cause this.

[error.log](https://github.com/user-attachments/files/17269884/error.log)

**Comment by dvankley** [comment]
Yeah, not a very helpful error message. Don't know why it doesn't give a lower level error than that.

Looks like an issue creating the `SyncHelper` class. It doesn't have a constructor function, so it's likely an issue with the [constructor params](https://github.com/dvankley/firefly-plaid-connector-2/blob/main/src/main/kotlin/net/djvk/fireflyPlaidConnector2/sync/SyncHelper.kt#L27-L33). Can you double/triple check that your `fireflyPlaidConnector2.firefly.personalAccessToken` and `fireflyPlaidConnector2.accounts` config variables are set correctly? And run your config file through a YAML validator?

You're also welcome to email me your (redacted) config file and I can take a look at it.

**Comment by dwildstr** [comment]
OK, this is embarrassing, but I never actually uncommented the lines in application.yml defining `fireflyPlaidConnector2.firefly.url` and `fireflyPlaidConnector2.firefly.personalAccessToken`, so the fact that the sync failed is unsurprising. I suppose to the extent there's an actual FPC issue here, it is that it's not raising an informative exception for an incomplete/invalid configuration, but indeed the major problem here is entirely my poor tweaking of the YAML. After an adjustment it works fine.
