### ISSUE TITLE
Plaid Developer environment deprecation

### ISSUE THREAD

**Issue by ch4ndu** [dvankley/firefly-plaid-connector-2#60]
Did you hear about this change happening sometime june this year? 
What are the alternatives for this? Can we use production for our use?

```Changes to our Development environment

Plaid will stop supporting its Development test environment by July 2024. If you have unused items in the Development environment, you’ll be provided with some credits to test in our Production environment in a limited capacity.

No action is required of you at this time.

What’s changing in 2024?
We’re working to provide developers and businesses with a simpler and more intuitive testing experience with Plaid’s products. As part of our work, we’ll be deprecating the Development test environment and introducing limited, free testing in our Production environment.

You can continue to test in the Development environment until we remove all existing Development items on June 20, 2024.

Please share this information with your technical team, and stay tuned for more updates when we’re ready for you to begin testing in Production.```

**Comment by dvankley** [comment]
Thanks for raising this. The first I heard of it was here: https://github.com/firefly-iii/firefly-iii/issues/7790#issuecomment-1877758371

As far as I know, the production environment should work fine with this connector, although I have not yet tested it. I will try to at some point before the cutover and fix any issues I encounter. Hopefully Plaid will provide more details on exactly what "limited, free testing in our Production environment" means. I do plan on continuing to support this project through the transition, for what that's worth.

From what I can find in some basic research online, Plaid charges around $.30/item/month for ongoing transaction sync and an additional one-time fee for new authentication. Items roughly correspond to financial institutions, so if you only connect to a handful of financial institutions, the monthly cost isn't unreasonable. I personally am willing to pay a dollar or two a month for this functionality, although I understand if that doesn't work for everybody.

**Comment by ch4ndu** [comment]
Right. I'm fine with paying the amount too 👍

**Comment by JeffHiggy** [comment]
With now under 2 months before the cut-off I decided I should tackle this in case the approval process takes a long time, it ended up being extremely easy and only took 1 business day. I only requested access to transactions so this may have sped things up. The only thing that might give some people some pause is they needed a scan of my drivers license, I understand why they'd need to verify my identity to prevent misuse but I know some people won't want to give this information.

As for the connector itself I've had no issues using it so far, just updated the url to production, put in my prod secret, and re-linked my banks. It's only been a few days, and I haven't been very active this week so there's only been 3 transactions from 2 institutions come in, but all imported fine with all the details.

Won't have my first bill until next month, but my billing page says what's already been said here, $0.30 per connected account/month, so for me that'd be $0.60/mo, we will see how they handle small charges like this.

**Comment by ch4ndu** [comment]
Nice....I'll try this out soon and report back.

**Comment by markwoodward86** [comment]
I also initiated this today. Will update.

**Comment by JeffHiggy** [comment]
Final update on this from me as I just got my first invoice, total of $0.90 (3 accounts @ $0.30/ea), no surprise extra costs.

In terms of functionality over the last month I've had no issues using this connector with the production environment, everything is working as it should and the same as it did with development.

**Comment by dvankley** [comment]
I have applied for prod access and will update the readme when it goes through and I can sanity check my config.

**Comment by dvankley** [comment]
Closing this as I've migrated to production successfully and updated the readme accordingly. Feel free to reach out with any additional questions.
