### ISSUE TITLE
Feature request: list of minimum feature when setting up Plaid dev account 

### ISSUE THREAD

**Issue by PingRen32** [dvankley/firefly-plaid-connector-2#67]
Opening plaid account now require to chose features under `Pick your Plaid products`, and without fully understanding the code I found it hard to move forward (maybe just select as much as possible since it charge by trigger anyway?)

<img width="820" alt="image" src="https://github.com/dvankley/firefly-plaid-connector-2/assets/20573489/af4ce448-c3e1-40ae-97ea-208a4904633b">

Above seems the widest combination for `Pay-as-you-go plan`. Would be greate to have a "minimum requirement" list of things for tis connector to function.

**Comment by dvankley** [comment]
Hm, I thought I had more time before they did the cutover. The website still shows the "free" plan as an option; did that not work for you?

I believe all you should need is the "Transactions" product. This connector does not call the "Recurring Transactions" or "Transactions Refresh" endpoints.
If you intend to use the [initial balances](https://github.com/dvankley/firefly-plaid-connector-2#initial-balances) feature of the connector, you will also need the "Balances" product, although given that that's billed per-request it probably doesn't make sense to use it anymore.

Let me know if that works for you. Probably time for me to upgrade to production as well. I'll update the README when someone has confirmed that those selections work.

**Comment by PingRen32** [comment]
Thanks for the quick reply,

`The website still shows the "free" plan as an option; did that not work for you?`  Somehow I cant find this option once login to my account, the `Get started` just led me to the screenshot. a bit fishy...

I agree on the `per call` pricing seems holding the feature back, with a 5~ account refreshing daily this would already price monthly somewhere like a commercial app. I will probably still give it a try tho just for fun project. See if I can make any progress.

**Comment by dvankley** [comment]
>I agree on the per call pricing seems holding the feature back, with a 5~ account refreshing daily this would already price monthly somewhere like a commercial app.

How do you figure? At $.30/account/month, you'd be looking at $1.50/month, which is substantially less than the commercial options I'm aware of.

**Comment by PingRen32** [comment]
> > I agree on the per call pricing seems holding the feature back, with a 5~ account refreshing daily this would already price monthly somewhere like a commercial app.
> 
> How do you figure? At $.30/account/month, you'd be looking at $1.50/month, which is substantially less than the commercial options I'm aware of.

I was thinking of a weekly balance on top of transaction so around $2 so I can track my saving, when minium of rocket money (also based on plaid) around $4 per month. Feels a little bit overkill working through all trouble setting firefly up just for that end point security or just saving that bit each month(well this thought might be reason why I need a tool to monitor my spending lol)

**Comment by dvankley** [comment]
>I was thinking of a weekly balance pull on top of transaction so around $2 for me to track my saving, when minium of rocket money (also based on plaid) around $4 per month. Feels a little bit overkill working through all trouble setting firefly up just for that end point security or just saving that bit each month(well this thought might be reason why I need a tool to monitor my spending lol)

Hm, yeah, that's valid.

I am definitely disappointed by the paid cutover mandate after putting all the work into this connector, although I can't really blame Plaid for charging for use of their service. Fundamentally I tend to blame this all on the financial institutions for not establishing standard APIs or making them available to their actual customers.

I've considered building an integration for [SimpleFIN](https://beta-bridge.simplefin.org), which appears to be a bit more predictable in pricing (and generally cheaper) but haven't yet seen enough evidence to convince me it's worth it to migrate. I'm definitely open to other suggestions as well.

**Comment by Kvan7** [comment]
So update from Plaid support on how the change over to no dev will work:

> With the new limited Production environment, we’re no longer offering free Development testing items. Instead, new customers will be given a limited number of free API requests, per product.
> 
>     For any products enabled in Development which are not Production-enabled, you will get free API requests in limited Production
>     For any products enabled in Development that are Production-enabled (i.e. you have been billed for usage of this product), you will not get any free requests to the given product endpoints

So basically don't enable anything in prod June 20th, or at least don't do anything billable in prod until the 20th. Kinda rip for me, I should have just waited to get any of this setup until then but whatever, as mentioned it'll be like $1-3 which is not the worst i guess. 

Their message didn't give a number to how many "limited number of free API requests" would be, so idk if the setting up of `Transaction` and polling every 10 min would still run through that extremely quickly or if it's like a set amount per month, or so ridiculously large that it wouldn't matter unless you were running a company off it.

**Comment by dvankley** [comment]
> I was initially worried that this did use the Refresh endpoint and was worried about paying like $17 a day to run it at 10 min polling so I did set it to once a day polled, but it hasn't used the Refresh endpoint which is awesome so i'll probably bump it back up to 10 min after this month.

I believe the `Refresh` endpoint is used for manually forcing Plaid to refresh data from source institutions, as discussed further here: https://github.com/dvankley/firefly-plaid-connector-2/issues/69. Currently the connector doesn't use it at all, although at some point I may add in that capability as discussed on that other issue.

**Comment by dvankley** [comment]
>So update from Plaid support on how the change over to no dev will work:

Thanks, that's super useful information. I'll add that to the readme shortly.

**Comment by dvankley** [comment]
@Kvan7 I've finished my own migration to the production environment, which was driven by most of my institutions (US oauth) no longer working in dev. There's a decent chance you'd have had the same problem in "limited Production," so I wouldn't sweat moving over early.

**Comment by dvankley** [comment]
Closing this as I've migrated to production successfully and updated the readme accordingly. Feel free to reach out with any additional questions.
