### ISSUE TITLE
Setting Port on Firefly URL

### ISSUE THREAD

**Issue by bmschwa** [dvankley/firefly-plaid-connector-2#87]
If I have my firefly listening on a non-standard port, is it possible to to specify a port somehow in the configuration....

From the uri builder [here](https://github.com/dvankley/firefly-plaid-connector-2/blob/7b453bc2e6860bb62d4e173c3548e28a5abb7193/src/main/kotlin/net/djvk/fireflyPlaidConnector2/api/firefly/infrastructure/ApiClient.kt#L166) I don't think its possible today.

**Comment by dvankley** [comment]
Yeah, that's not possible with the current code.
Have you considered using a reverse proxy? If you've considered it and it doesn't work for you, I'm happy to add this as a feature request. Should be fairly easy to add.

**Comment by bmschwa** [comment]
I ended up using subdomains and I'm cool now... now fighting with plaid!
