### ISSUE TITLE
Ability to configure poll mode to allow sync with an item to fail without failing the entire run

### ISSUE THREAD

**Issue by dkichler** [dvankley/firefly-plaid-connector-2#91]
I've been using this for a while and unfortunately also use CIBC as an institution and hence am affected by regular failures from their API.  This impacts the rest of my institutions from continuing to update if ever one lapses.  

I think it would be useful to allow the sync to continue in the case of an item failing, to allow other items to continue updating as long as credentials remain valid.

**Comment by JeffHiggy** [comment]
I have the same issue with CIBC, I just setup multiple instances of the connector, one for CIBC and another for the others. And the restart policy I have set just restarts the container anyway.

(Although I don't have the CIBC instance running since plaid never pulls new transactions anyway)

**Comment by dkichler** [comment]
> I just setup multiple instances of the connector, one for CIBC and another for the others. 

Not a bad workaround.

> (Although I don't have the CIBC instance running since plaid never pulls new transactions anyway)

I've found that as long as you keep the connection "fresh" (ie fixing the MFA once daily or every other day) it will still manage to pull txns.  However, leave it for a few days or a week and the connection grows stale and a `transcations/refresh` is needed to get things flowing again.  

The other issue I've noticed from CIBC (not sure if this affects other Plaid institutions as well) is that it seems to post the same txn on both the Transaction _and_ Posted date and fails to recognize them as the same transaction, effectively resulting in a duplicate (perhaps this is a bug/limitation in Plaid itself).

**Comment by dvankley** [comment]
Fixed in https://github.com/dvankley/firefly-plaid-connector-2/pull/92. Thanks, @dkichler.
